### PR TITLE
Standardize unit test file names

### PR DESCRIPTION
**Pull request by deepakrkris**

### CODE REVIEW

**Review by NickNaso — APPROVED** [review]
LGTM. Could you please add little description about what this PR do. This could help us in the future.

**Comment by mhdawson** [comment]
@deepakrkris just waiting for the updates to the comments before landing.

**Comment by deepakrkris** [comment]
@mhdawson @NickNaso @gabrielschulhof @KevinEady,
 I have included a detailed commit message about the changes and linter fixes.

**Comment by mhdawson** [comment]
@deepakrkris thanks, landing now

**Comment by mhdawson** [comment]
Landed as cbac3aac5d4c80d6e9a8e79a4bdb10dff4221172

**Pull request closed without merging**
