### PR TITLE
Make CleanupHook public

### PR DESCRIPTION
**Pull request by julianmesa-gitkraken**
Make CleanupHook public.
Added default constructor to make easier store the hook in a member class var.
Also fixed a bad #endif position.

This PR fix [issue 1238](https://github.com/nodejs/node-addon-api/issues/1238)

### CODE REVIEW

**Comment by julianmesa-gitkraken** [comment]
> Overall LGTM. Thank you for working on this!
> 
> Would you mind adding a test that verifies the `CleanupHook` is available to be used as a class member?

@legendecas Added a very simple test, not sure if this is enough

**Review by legendecas — APPROVED** [review]
Thank you for working on this!

**Comment by mhdawson** [comment]
Seems like since the docs do identify the type which is returned it should be public so agree this makes sense.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Landed as 39267baf1ba985275f74991fef6faac2ccf8e495

**Pull request closed without merging**
