### PR TITLE
doc: fixup to meet lint rules

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
Fix a couple of the files, starting alphabetically + clang-format since I need to tweak on my machine and it triggers linter errors.

**Comment by mhdawson** [comment]
Looks like all the failures are an issue related to github not having 16.04 machines.

@NickNaso wondering if you could review so I can land.

**Review by NickNaso — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Landed as 4351bffd537eab927226bf6f9b66cd385a049a43

**Pull request closed without merging**
