### PR TITLE
Conversion tool now enables c++ exceptions by default, disables them with a flag

### PR DESCRIPTION
**Pull request by anisha-rohra**
Issue brought up here: https://github.com/nodejs/node-addon-api/issues/135

### CODE REVIEW

**Comment by mika-fischer** [comment]
Could you integrate the flag mentioned here? https://github.com/nodejs/node-addon-api/issues/85

Otherwise, there will be hard-to-debug failures on Windows.

**Comment by anisha-rohra** [comment]
@mika-fischer Updated! Will test on a windows machine to confirm within the day.

**Comment by mhdawson** [comment]
@anisha-rohra have you validated on a windows machine yet ?

**Comment by mhdawson** [comment]
@anisha-rohra it would be nice to close this one out. I think John B on our team managed to get access to one of our windows machines to validate a Windows issue so maybe he can help you out with access.

**Comment by anisha-rohra** [comment]
@mhdawson checked on windows machine, the windows specific code works. Also resolved conflicts with recent changes to the script so it should be good to go.

**Comment by mhdawson** [comment]
@anisha-rohra could you squash down to one commit ?  For some reason I get a conflict when I try to land even though git seems to think it should be able to land ok.

**Comment by anisha-rohra** [comment]
@mhdawson Think it should be fine now? Merged with master then reapplied my changes on top.

**Comment by mhdawson** [comment]
Landed as 133754ca46fd2a0a5ca7f0a2d13b6e004d63a44c

**Pull request closed without merging**
