### PR TITLE
scopes: make failure of closing scopes fatal

### PR DESCRIPTION
**Pull request by legendecas**
But not ignoring these failures.

### CODE REVIEW

**Comment by legendecas** [comment]
I don't think it would affect the existing working code. Yet it would be helpful to debug possibly misusage of `Napi::HandleScope`s like:

```c++
Value doubleCloseScope(const CallbackInfo& info) {
  Env env = info.Env();
  HandleScope scope(env);
  HandleScope scope2 = scope; // this one would be closed with status `napi_handle_scope_mismatch` silently
  return env.Undefined();
}
```

**Comment by mhdawson** [comment]
@gabrielschulhof if you agree it's unlikely to affect working code I'm ok with it.

**Comment by mhdawson** [comment]
Discussion in N-API team meeting today was that this is directly related to https://github.com/nodejs/node-addon-api/pull/565.  We don't believe that the close should fail except for the case where it had been copied which will no longer be possible.

So we don't believe this will not break any existing code and its ok to land as a semver Patch fixing an bug.

**Comment by mhdawson** [comment]
We did discuss and this should land as a SemVer major even though it should not affect any existing code.

**Comment by mhdawson** [comment]
Landed as ce139a05e867e5b46cd8971324263823560a89f9

**Pull request closed without merging**
