### PR TITLE
src: fix leak in ObjectWrap instance set/getters

### PR DESCRIPTION
**Pull request by KevinEady**
Fixes: #891

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM, thanks for investigating and fixing

**Comment by KevinEady** [comment]
Flakey tests cause the run failure maybe @mhdawson ?

**Comment by mhdawson** [comment]
@KevinEady it is a bit worrying that we seem to get intermittent failures. We saw that for a while in the CI but then it went away without me being able to figure out the cause.  Might be worth running a few times locally (say 10 times) to make sure it does not recreate.

**Review by gabrielschulhof — APPROVED** [review]
Good catch!

**Comment by mhdawson** [comment]
Landed as: a575a6ec60652689c21c744e8da2fb1ecae4350a

**Pull request closed without merging**
