### PR TITLE
src,doc: refactor to replace typedefs with usings

### PR DESCRIPTION
**Pull request by RaisinTen**

### CODE REVIEW

**Comment by mhdawson** [comment]
What level of compiler support does this syntax require?

**Comment by RaisinTen** [comment]
@mhdawson all compilers support this except except Digital Mars C++.
See row 11 (Template aliases) of: https://en.cppreference.com/w/cpp/compiler_support#cpp11

How do I fix the lint error? Running this doesn't change anything for me locally:
```zsh
❯ npm run lint:fix

> node-addon-api@3.1.0 lint:fix
> git-clang-format '*.h', '*.cc'

no modified files to format
```

**Comment by mhdawson** [comment]
One more question, is there anything that you can do with a typedef definition that you can't do with the using def ?

**Comment by RaisinTen** [comment]
@mhdawson no there isn't.
I preferred using `using` here because it can do whatever `typedef` does + it also allows `template`s.

**Comment by legendecas** [comment]
> How do I fix the lint error? Running this doesn't change anything for me locally:

The lint is comparing the local changes with the main branch. Please have a check on your local main branch and dev branch are up to date with the GitHub one.

**Comment by RaisinTen** [comment]
> The lint is comparing the local changes with the main branch. Please have a check on your local main branch and dev branch are up to date with the GitHub one.

@legendecas Yes, they are up to date. Turns out, `getNativeBinary()` of `node_modules/clang-format/index.js` can't find the `clang-format` binary on my machine because it's an unsupported architecture I guess (`ia32`). `tools/clang-format.js` ends up swallowing the error because it checks for `error` instead of `stderr` of the spawned `ChildProcess`.

I tried to copy and paste the linter error log into a file and `git apply` it but unfortunately it prints:
```
error: corrupt patch at line 48
```
:/

**Comment by RaisinTen** [comment]
PR to fix the error detection: https://github.com/nodejs/node-addon-api/pull/914

**Comment by RaisinTen** [comment]
I could apply the patch from the [logs](https://github.com/nodejs/node-addon-api/runs/1919880040?check_suite_focus=true) of the failed style check run and now the style check passes too.

However, it seems to have added some more changes than what I intended (like indenting some other parts of the code).
Would it make sense to run clang-format on the full codebase and make a PR to fix the style so that other PRs don't have to make unrelated style changes?

PTAL.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by NickNaso — APPROVED** [review]
Some notes about the reasons that pushed me to approve this PR:

It's possible to define a new name for an existing type with both:
- `typedef` (We call this declaration `typedef` and the resulting name `typedef-name`)
- `using` (We can call this decalration  `alias desclaration`)

The `using` alternative is more readable because you always have the type name on the left side of the `=`. 

Unlike a `typedef` an alias declaration can be templated to provide a conveninet name for a family of types. This is available since C++11 and is called alias template.

**Comment by mhdawson** [comment]
Need to run on our CI to make sure all the older compilers support using before landing.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3744/ |  |
| v15.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3743/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3742/ |  |
| v13.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3741/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3740/ |  |
| v11.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3739/ |  |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3738/ |  |

**Comment by mhdawson** [comment]
@NickNaso thanks for running the CIs

The failures on 11 seem unrelated to this PR as you mention, possibly because of something that would have been backported to 10.x but not 11.

Checking the table in https://en.cppreference.com/w/cpp/compiler_support#cpp11 it also seems to confirm that all of the minimum levels for Node.js 10.x support using so I think this is good to land.

**Comment by mhdawson** [comment]
Landed as 71494a49a31bde6e4400bfde20486e2a316577a6

**Pull request closed without merging**
