### PR TITLE
Add more documentation

### PR DESCRIPTION
**Pull request by jasongin**
- Add doc-comments to the `Boolean`, `Number`, `Symbol`, `Object`,
   and `PropertyLValue` classes.
 - Make `PropertyLValue` a nested class inside `Object`, because it
   is only ever used by `Object` and would almost never be referenced
   explicitly.
 - Make some `Object` method parameter names more consistent.
 - Add missing `Object::Set()` overload.

### CODE REVIEW

**Comment by mateodelnorte** [comment]
Are there any minimalist examples of using node-addon-api anywhere?

**Comment by jasongin** [comment]
@mateodelnorte Check out [`generator-napi-module`](https://github.com/digitalinfinity/generator-napi-module) - it is a yeoman generator that helps you get started with a basic "hello world" module that uses `node-addon-api`.

**Comment by mateodelnorte** [comment]
thanks @jasongin. that gets me part of the way there! but I still get syntax errors on node-gyp rebuild: 

https://gist.github.com/mateodelnorte/821335aeb1d4e6a4dfdb594f0386dc97

**Comment by jasongin** [comment]
I published the updated documentation to https://nodejs.github.io/node-addon-api/

**Pull request merged**
