### PR TITLE
Write tests for Number class

### PR DESCRIPTION
**Pull request by romandev**
The new tests cover a part of the basic type conversion from JavaScript
type to native type.

### CODE REVIEW

**Comment by romandev** [comment]
@mhdawson PTAL

**Comment by romandev** [comment]
@mhdawson,
It's enough short, but I reduced the count more in my latest patch.
The average loop count will be 400.

**Comment by mhdawson** [comment]
@romandev thanks, will plan to land when I have some free time.

**Comment by mhdawson** [comment]
Landed as 8e31e242098c61db4bf3e9a0dc801b5e51dd7fc8

**Pull request closed without merging**
