### PR TITLE
Add ArrayBuffer::Detach() and ::IsDetached()

### PR DESCRIPTION
**Pull request by tniessen**
I don't know what the proper guard is, seems like `NAPI_EXPERIMENTAL` and `NAPI_VERSION` are not good enough.

Refs: https://github.com/nodejs/node/pull/29768
Refs: https://github.com/nodejs/node/pull/30613

### CODE REVIEW

**Comment by legendecas** [comment]
`NODE_MAJOR_VERSION` can be used in tests to guards on Node.js major version so that no-back-ported Node.js release can work on CI.

**Comment by mhdawson** [comment]
@tniessen do you need any more info to progress this?

**Comment by mhdawson** [comment]
@tniessen are you still planning to work on this?

**Comment by mhdawson** [comment]
@tniessen np, just wanted to check in as I was doing some cleanup on the issues.

**Comment by mhdawson** [comment]
@tniessen ping.

**Comment by tniessen** [comment]
Sorry it took me so long to get back to this!

**Comment by mhdawson** [comment]
CI run on 10.x as oldest LTS: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/3022/

CI run on head: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/3025/

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Looks good landing

**Comment by mhdawson** [comment]
Landed as c9563caa25bfb208f4dd8f0f0e55f0861bf057dc

**Pull request closed without merging**
