### PR TITLE
Exit test script with exit code 1 in case of failure

### PR DESCRIPTION
**Pull request by addaleax**
Just a small thing I noticed.

(I’m currently trying to set up Travis/AppVeyor CI support, btw – I might open a WIP PR shortly. It won’t work for the Node.js org repo, but it’s something that could be enabled in the forks we are working from.)

### CODE REVIEW

**Comment by jasongin** [comment]
> I’m currently trying to set up Travis/AppVeyor CI support, btw – I might open a WIP PR shortly.

Cool. I was planning to do that soon, but since you're on that I'll work on more documentation instead.

> It won’t work for the Node.js org repo

Why not? Can we not enable the necessary integration in this repo?

**Comment by addaleax** [comment]
> > It won’t work for the Node.js org repo

> Why not? Can we not enable the necessary integration in this repo?

We can’t give Travis access to the organization because doing so would give it access to private repos containing sensitive information… we’ve talked about this a lot :/

**Comment by jasongin** [comment]
That's unfortunate. So should we look into setting up Jenkins (ci.nodejs.org) instead?

**Comment by addaleax** [comment]
That’s what we have typically been doing so far, yes…

**Comment by mhdawson** [comment]
The other issue with Travis is that it does not provide the platform coverage we have in the Node.js CI.

I do have it on my list to set something up, just have not had time to get to it yet.

Having said that @jasongin we have set to be able to let WG's manage edit jobs so if want to help setup the jenkins job I can create the empty job and you should be able to configure it.

**Comment by kkoopa** [comment]
Travis still works without giving access, it is onlt the GitHub hooks that don't. We use Travis and AppVeyor in NAN. Just have to remember to check the build status from Travis or AppVeyor site. Travis were nice enough to also give us access to OS X as well when approached.

**Comment by jasongin** [comment]
@kkoopa Without hooks, then do you have to manually _start_ the CI also?

**Comment by kkoopa** [comment]
No, all it affects is that the CI status thing is not visible in pull requests.

**Comment by kkoopa** [comment]
Regarding travis permissions, they list them:
https://docs.travis-ci.com/user/github-oauth-scopes/

read:org (read-only) When you’re logged in on Travis CI, we show you all of your repositories, including the ones from any organization you’re part of. The GitHub API hides any organizations you’re a private member of without this scope. So to make sure we show you all of your repositories, we require this scope. **Note that this scope allows access to the basic information about both private and public repositories, but not on any of the data or code stored in them.**

**Comment by addaleax** [comment]
> Travis were nice enough to also give us access to OS X as well when approached.

Just fyi, I’m pretty sure it’s no longer necessary to ask them, OS X is now supported for all packages that want it. :)

**Comment by addaleax** [comment]
Sure, I’ll close this. :)

**Pull request closed without merging**
