### PR TITLE
Update to new error helper signatures in n-api

### PR DESCRIPTION
**Pull request by mhdawson**
Update to use new signatures
Update copies of n-api files so they match. I've not done
a direct copy because more work is needed given that the
n-api files now use node internals.  I have updated so that
they are consistent and will build ok with respect to
this specific chaange. I took this approach to minimize
the time the wrapper is broken by the breaking change
on the n-api side.

Also note that we'll need follow on work to expose the ability to add the code
when using the wrapper but I think that is best left to a follow on PR
so that we can limit the time the wrapper is broken.

### CODE REVIEW

**Comment by mhdawson** [comment]
Related to https://github.com/nodejs/node/pull/13988

**Comment by jasongin** [comment]
> more work is needed given that the n-api files now use node internals

That work is done already in https://github.com/nodejs/node-addon-api/pull/70. Looks like it's almost ready to merge. Maybe you should wait to rebase on top of that?

**Comment by kfarnung** [comment]
@jasongin I could split out the changes from my PR to land it sooner.

**Comment by kfarnung** [comment]
I opened #79 with my changes split out from #70.

**Comment by mhdawson** [comment]
Landed https://github.com/nodejs/node-addon-api/pull/79 and then rebased this PR and validated with latest version of node that has the error changes.

**Comment by mhdawson** [comment]
@jasongin @kfarnung once I get one approval I'll land

**Comment by kfarnung** [comment]
Yesterday I was seeing a test failure on windows with node 8.1.4, I'll take a look today and see if I can figure out what's going on.

**Comment by mhdawson** [comment]
Landed as 179d13529cca85ef7228ba779bc153cb6925003f

**Pull request closed without merging**
