### PR TITLE
Update files from node

### PR DESCRIPTION
**Pull request by kfarnung**
* Added `node_internals.cc/h` to shim missing internal functions

### CODE REVIEW

**Comment by kfarnung** [comment]
@jasongin @mhdawson I split out the node_internals changes from #70.

**Comment by kfarnung** [comment]
Looks like we finally have a signature issue with node 4:

https://travis-ci.org/kfarnung/node-addon-api/jobs/253006582

```
> node-addon-api@0.4.0 pretest /home/travis/build/kfarnung/node-addon-api
> node-gyp rebuild -C test

make: Entering directory `/home/travis/build/kfarnung/node-addon-api/test/build'
  CXX(target) Release/obj.target/node-api/../src/node_api.o
../../src/node_api.cc:625:3: error: no member named 'Get' in 'v8::Persistent<v8::ObjectTemplate, v8::NonCopyablePersistentTraits<v8::ObjectTemplate> >'
  ENV_OBJECT_TEMPLATE(env, function_data, otpl, v8impl::kFunctionFieldCount);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/node_api.cc:58:48: note: expanded from macro 'ENV_OBJECT_TEMPLATE'
      (destination) = env->prefix ## _template.Get(isolate);       \
                      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../src/node_api.cc:651:3: error: no member named 'Get' in 'v8::Persistent<v8::ObjectTemplate, v8::NonCopyablePersistentTraits<v8::ObjectTemplate> >'
  ENV_OBJECT_TEMPLATE(env, accessor_data, otpl, v8impl::kAccessorFieldCount);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/node_api.cc:58:48: note: expanded from macro 'ENV_OBJECT_TEMPLATE'
      (destination) = env->prefix ## _template.Get(isolate);       \
                      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../src/node_api.cc:2087:3: error: no member named 'Get' in 'v8::Persistent<v8::ObjectTemplate, v8::NonCopyablePersistentTraits<v8::ObjectTemplate> >'
  ENV_OBJECT_TEMPLATE(env, wrap, wrapper_template, 2);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/node_api.cc:58:48: note: expanded from macro 'ENV_OBJECT_TEMPLATE'
      (destination) = env->prefix ## _template.Get(isolate);       \
                      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
3 errors generated.
make: *** [Release/obj.target/node-api/../src/node_api.o] Error 1
make: Leaving directory `/home/travis/build/kfarnung/node-addon-api/test/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvs/node/4.8.4/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvs/node/4.8.4/x64/bin/node" "/home/travis/.nvs/node/4.8.4/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "test"
gyp ERR! cwd /home/travis/build/kfarnung/node-addon-api/test
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Test failed.  See above for more details.


The command "npm test $NPMOPT" exited with 1.
```

**Comment by kfarnung** [comment]
Opened a PR in node:  https://github.com/nodejs/node/pull/14211

**Comment by kfarnung** [comment]
@mhdawson I added the missing macro/functions for your change.  I rebased your PR against this code and everything built successfully.

**Comment by mhdawson** [comment]
Landed as 92d14c0cf038c6af5ad41acc906f9895cd37838d

**Pull request closed without merging**
