### PR TITLE
release: v7.0.0

### PR DESCRIPTION
**Pull request by KevinEady**
Update package and documentation for release v7.0.0 according to [Creating a Release](https://github.com/nodejs/node-addon-api/blob/de5c899400fffbc2265d66c687f4f7ce585925cd/doc/creating_a_release.md)

### CODE REVIEW

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| main | https://ci.nodejs.org/job/node-test-node-addon-api-new/7575/ |  |
| v20.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/7576/ |  |
| v18.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/7577/ |  |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/7578/ |  |

**Comment by KevinEady** [comment]
@NickNaso should the CI jobs be ran on `main` once this is merged or is it sufficient to run on this PR? I was planning on the former but I see you started some jobs 😄

**Comment by NickNaso** [comment]
@KevinEady Yes I saw you updates and all seems good so I ran the CI. I think that we should also run the CI on ` main` after the merge of the PR.

**Comment by KevinEady** [comment]
Merging after 24h with only one approval to complete release

**Pull request merged**
