### PR TITLE
Fix code format in tests

### PR DESCRIPTION
**Pull request by tniessen**
This fixes a few code formatting issues in `test/`.

### CODE REVIEW

**Comment by legendecas** [comment]
Maybe linters can be introduced to the project?

**Comment by tniessen** [comment]
That is generally a good idea!

**Comment by NickNaso** [comment]
We could use [clang-format](https://www.npmjs.com/package/clang-format). We can install it like dev dependencies. What do you think?

**Comment by tniessen** [comment]
I have never used clang-format. Most Node.js projects use ESLint for the JS parts, and in core we use [cpplint](https://github.com/nodejs/node/blob/master/tools/cpplint.py) for C++. Seems like we also have [a partial ruleset for clang-format](https://github.com/nodejs/node/blob/master/.clang-format), though.

**Comment by mhdawson** [comment]
I think this can land while we figure out if we can add linters.

**Comment by gabrielschulhof** [comment]
CI:

| Version | Job | Status |
|---:|---|---|
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/1378/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/1379/ | ✓ |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/1380/ | ✓ |
| v8.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/1381/ | ✓ |

**Comment by gabrielschulhof** [comment]
Landed in 0e7483eb7b926e67db83632a5a5baf9c9b8d525f.

**Pull request closed without merging**
