### PR TITLE
test: fixup testing for specific N-API version

### PR DESCRIPTION
**Pull request by mhdawson**
Fixup testing for a specific N-API version
and document.

### CODE REVIEW

**Comment by mhdawson** [comment]
@KevinEady, @legendecas I don't think the linting is working correctly. It's reporting problems in files I've not changed.

**Review by NickNaso — APPROVED** [review]
LGTM

**Comment by legendecas** [comment]
@mhdawson the check is comparing the local master with the current PR branch. So on the CI, it will compare with the latest master. We have to update the PR branch with the latest master branch to make sure the diff do not include changes landed on master after the fork of the development branch.

**Comment by mhdawson** [comment]
@legendecas I'm not following what we need to fix this?

**Comment by legendecas** [comment]
＠mhdawson Sorry but maybe I'm misunderstanding the problem. I didn't find the CI is failing. Can you help me explain what failure you're referring to?

**Comment by mhdawson** [comment]
@legendecas it was reporting failures when I ran locally and I had to add the comment to ingore the pre-commit checks.

**Comment by legendecas** [comment]
@mhdawson ok. The linter compares the current working branch with the local master branch. If the local master branch is not up to date or contains the latest commits that not linted, which commits the working branch doesn't include, then the diff will include those _unrelated_ changes and the linter will complain about them.

**Comment by mhdawson** [comment]
@legendecas that may cause people confusion/trouble since I'm not sure how many people keep their local master branch up to date.

**Comment by KevinEady** [comment]
@mhdawson FWIW, the script allows you to specify a process env [`CLANG_FORMAT_START`](https://github.com/nodejs/node-addon-api/blob/master/tools/clang-format.js#L7), eg `upstream/master` .. but yes, it definitely caused me confusion/trouble, which is how I stumbled across this setting 🤷

**Comment by legendecas** [comment]
The local master branch might not always tracking nodejs/node-addon-api but rather someones-fork/node-addon-/api so I didn't comparing with local upstream/master or some-local-remote/master.

Maybe we can print instructions when the check failed how to fix the local check to improve the experience.

**Pull request merged**
