### PR TITLE
Minor doc fixes

### PR DESCRIPTION
**Pull request by bmacnaughton**
As I was working through the docs I made edits when I noticed typos, misspellings, or in the case of object.md, incorrect information.

I find myself doing a bit more research than I wanted to in a few cases and wondered what your thoughts were on expanding some of the docs to include examples as opposed to (mostly just) API.

Here's a list of items that I found myself experimenting with to get something working because I couldn't deduce from the docs alone what I needed to do.

- external data
- DefineClass examples for Instance/Static methods/properties
- property_descriptors
- how to use class_property_descriptors

(actually I didn't get the last two working and just found a way around the issue but those were my first approaches.)

If you're open to providing more examples for the first two let me know where you think they belong and I'll work on some.

Thanks for the excellent doc. When I compare this to trying to get Nan working over a year ago it's night and day.

### CODE REVIEW

**Comment by mhdawson** [comment]
We are definitely open to adding more examples info to help clarify the concepts.  Will need a bit more time to take a look to see where they might go.  @NickNaso might also have some suggestions.

**Comment by NickNaso** [comment]
Hi @bmacnaughton,
if you want add examples on documentation, you can refer on patterns the we follow in this part of the actual documentation:
https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md#example
https://github.com/nodejs/node-addon-api/blob/master/doc/error_handling.md#examples-with-c-exceptions-enabled
https://github.com/nodejs/node-addon-api/blob/master/doc/async_context.md#example

In general we added the `Example` section after the API documentation. Feel free to be expressuve as you want. If your example are too complex maybe we need to consider the idea of creating an example to push on node-addon-example repo.

**Comment by bmacnaughton** [comment]
Thanks. I'll take a look and think about it a bit.

**Comment by NickNaso** [comment]
@bmacnaughton  please if it could help you feel free to open an issue about that so we can sharing all the ideas together.

**Comment by DaAitch** [comment]
I hope I don't mix this, but as long as documentation is maintained twice, both should be up to date, but in the future we want to get rid of `/doc` (with #368), correct? So we should get this done soon?

**Comment by mhdawson** [comment]
Landed as c629553cd7b08ea9e56a55176583219ee19a8a86.  @bmacnaughton thanks for the updates.

**Pull request closed without merging**
