### PR TITLE
Implement Object::HasOwnProperty() method

### LINKED ISSUE #175: HasOwnProperty missing from the C++ wrappers
There's a `napi_has_own_property`, but no `HasOwnProperty()`

I also couldn't find a `GetOwnPropertyNames` (that nan has), nor a napi_get_own_property_names.

### PR DESCRIPTION
**Pull request by romandev**
Need HasOwnProperty() that is a wrapper for napi_has_own_property().
This change fixes #175 issue.

### CODE REVIEW

**Comment by romandev** [comment]
@mhdawson PTAL

**Comment by mhdawson** [comment]
@NickNaso FYI, to make sure we add these methods to doc as well.

**Comment by addaleax** [comment]
Looks good, but imo this should really be `HasOwnProperty()`, for consistency with `HasOwnProperty()` in the spec, `Object.hasOwnProperty`, `napi_has_own_property()`, Nan’s `HasOwnProperty()` and many, many more

**Comment by romandev** [comment]
@addaleax, @mhdawson I renamed HasOwn() with HasOwnProperty() as per above comment. Is it fine?

**Comment by addaleax** [comment]
Landed in c9a674f110ab81a85f0979d60037561d89120d47

**Pull request closed without merging**
