### PR TITLE
test: refactor remove repeated execution index.js

### PR DESCRIPTION
**Pull request by RaisinTen**
Since the only job of the main thread is to supply the correct
command-line args to the child thread, here is a refactor to do
just that. The generation and execution of the `testModule` is done by
the child thread.

### CODE REVIEW

**Comment by RaisinTen** [comment]
Can someone please review this?

**Comment by mhdawson** [comment]
@RaisinTen maybe you can come to the N-API team meeting this Friday to walk us through it.  It's a "nice to have" and obviously nobody has had time to get around to it so that might help move it forward.

**Comment by mhdawson** [comment]
@RaisinTen absolutely (althouhg its zoom).  Just in case you need it: https://zoom.us/j/363665824
https://hangouts.google.com/hangouts/_/event/c0eevtrlajniu7h8cjrdk0f56c8 and the meeting is Friday at 11 EST.

**Comment by mhdawson** [comment]
@RaisinTen and to be 100% clear, the only option is zoom even though there are other links in the calendar entry, I've just updated it so that its clearer that they are generally not used.

**Comment by RaisinTen** [comment]
@mhdawson thank you for updating it. Looking forward to the meet.

**Comment by RaisinTen** [comment]
@mhdawson I was a little confused about the timing. Is the node calendar timing yet to be updated?

**Comment by mhdawson** [comment]
The calendar time should be correct. 11:00 ET

**Comment by RaisinTen** [comment]
@mhdawson hmm, when I saved the event to my calendar, it showed the correct time indeed. However, the time shown at nodejs.org/calendar is still different. What time standard does it follow?

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by gabrielschulhof — APPROVED** [review]

**Review by NickNaso — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Landed as 744705f2eb20fa85afb740d4814bfa69018924ac

**Pull request closed without merging**
