### PR TITLE
chore: use eslint directly

### PR DESCRIPTION
**Pull request by legendecas**
`tools/eslint-format` was not failed on https://github.com/nodejs/node-addon-api/pull/1613 but failed on the main branch.

Since the diff on applying the eslint is trivial, let's apply eslint on all files.

### CODE REVIEW

**Comment by KevinEady** [comment]
Hmm, should the formatting changes have been found in our "format everything" branch https://github.com/nodejs/node-addon-api/pull/1160 ? Or were there new rules added since 1160 landed (May 2022)?

**Comment by legendecas** [comment]
https://github.com/nodejs/node-addon-api/pull/1613 updated the eslint and plugins version. However, `tools/eslint-format` only checks on JS files changed in a PR -- where #1613 didn't change any JS files. `eslint-format` does not apply new eslint and plugins on existing files.

**Review by KevinEady — APPROVED** [review]
LGTM! 🎉

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
