### PR TITLE
Implement CallbackScope class

### PR DESCRIPTION
**Pull request by romandev**
This is a wrapper class to support the following N-APIs.
  - napi_open_callback_scope()
  - napi_close_callback_scope()

Refs: https://nodejs.org/api/n-api.html#n_api_napi_open_callback_scope

### CODE REVIEW

**Comment by romandev** [comment]
If someone has a permission, please add `DO NOT MERGE` label.
This PR is still under development.
While I implement this feature, I have some questions.
So, I'd like to discuss about it. (I'll investigate it deeply myself and raise this issue again)

**Comment by mhdawson** [comment]
@romandev thanks for picking this up :)

**Comment by romandev** [comment]
Addressed your comments. Thank you for review!

**Comment by romandev** [comment]
Could you please remove `do not land` label? (to avoid confusing)

**Pull request closed without merging**
