### PR TITLE
Create a doc for migration

### PR DESCRIPTION
**Pull request by sampsongao**
Feel free to comment about things that are not covered here.

### CODE REVIEW

**Comment by mhdawson** [comment]
@sampsongao are you going to add the paragraph requested by @mcollina ? I'm waiting on that to do a thorough review.

**Comment by sampsongao** [comment]
Will do that next week. Currently busy with some other stuff.

**Comment by mhdawson** [comment]
@sampsongao ping ?

**Comment by mhdawson** [comment]
@sampsongao are you still going to be able to update ?

**Comment by sampsongao** [comment]
I don't have anything to update on my side.

**Comment by mhdawson** [comment]
@mcollina if your comments have been addressed can you review/approve?

**Comment by mhdawson** [comment]
Landed as 7f3ca03b8e30ecb146cb95d9c2e1f2dcb2d1ab6e

**Pull request closed without merging**
