### PR TITLE
src: rename N-API with Node-API on comments

### PR DESCRIPTION
**Pull request by NickNaso**
Fixes issue https://github.com/nodejs/node-addon-api/issues/952
In this PR I renamed N-API to Node-API in all the comments in the source code.

### CODE REVIEW

**Review by legendecas — APPROVED** [review]
LGTM. I assume most of the unrelated changes are subject to linter complaints?

**Comment by NickNaso** [comment]
> LGTM. I assume most of the unrelated changes are subject to linter complaints?

Yes,

**Review by gabrielschulhof — COMMENTED** [review]
This PR does more than rename N-API to Node-API. There are also a bunch of whitespace changes. Would it be OK to just stick to the renaming? Otherwise it may create some churn.

**Comment by gabrielschulhof** [comment]
Oh. Didn't see the convo. NM.

**Review by gabrielschulhof — APPROVED** [review]

**Comment by gabrielschulhof** [comment]
CI:

| Version | Job | Status |
|---:|---|:---:|
| master | https://ci.nodejs.org/job/node-test-node-addon-api-new/3853/ |  |
| v15.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3854/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3855/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3856/ |  |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/3857/ |  |

**Comment by gabrielschulhof** [comment]
Landed in 628023689a66e63ce70fada3e8e633b85c482046.

**Pull request closed without merging**
