### PR TITLE
[WIP] Added Object::New() taking a list of properties.

### PR DESCRIPTION
**Pull request by NickNaso**
This PR fixes https://github.com/nodejs/node-addon-api/issues/603
- [x] Implementation
- [x] Documentation
- [ ]  Tests

### CODE REVIEW

**Comment by mhdawson** [comment]
@NickNaso are you still working on this one?

**Comment by NickNaso** [comment]
@mhdawson Yes I'm working on it.

**Comment by devsnek** [comment]
can this also take a prototype argument?

**Comment by seishun** [comment]
- Are you still working on this?
- Would this be a viable replacement for multiple calls to `Napi::Object::Set`?

**Comment by NickNaso** [comment]
Hi @seishun ,
I'm honest I forgot of this PR. Yes this should be a replacement for multiple calls on `Napi::Object::Set`.  Do you want to work on this ?

**Comment by seishun** [comment]
Consider this code:

```cpp
auto object = Napi::Object::New(env):
object.Set("foo", foo);
object.Set("bar", bar);
return object;
```

If understand correctly, this PR would let one rewrite it as the following (assuming `foo` and `bar` are numeric):

```cpp
return Napi::Object::New({
  Napi::PropertyDescriptor::Value("foo", Napi::Number::New(env, foo)),
  Napi::PropertyDescriptor::Value("bar", Napi::Number::New(env, bar))
});
```

That's hardly an improvement. Am I missing something?

**Pull request closed without merging**
