### PR TITLE
test: added test case to check the addon building process.

### PR DESCRIPTION
**Pull request by NickNaso**
This PR complete the work done on PR **https://github.com/nodejs/node-addon-api/pull/766**.
The PR introduce some test to check to build of an addon.
Refs: 
- Issue https://github.com/nodejs/node-addon-api/issues/769
- Issue https://github.com/nodejs/node-addon-api/issues/765

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@NickNaso there seem to be failures on 10.x for windows: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/2728/nodes=win-vs2017/

and it seems to fail with most platforms on 15.x -> https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/2727/

What is see when I try to run locally is:

```shell
> node test

Testing with N-API Version '6'.
Starting test suite

Running test 'addon_build'
Error: Command failed: npm install
(node:105097) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
(Use `node --trace-deprecation ...` to show where the warning was created)
npm WARN npm npm does not support Node.js v15.0.0-pre
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mhdawson/.npm/_logs/2020-09-04T20_13_42_420Z-debug.log

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install',
  stdout: '',
  stderr: '(node:105097) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.\n' +
    '(Use `node --trace-deprecation ...` to show where the warning was created)\n' +
    'npm WARN npm npm does not support Node.js v15.0.0-pre\n' +
    'npm WARN npm You should probably upgrade to a newer version of node as we\n' +
    "npm WARN npm can't make any promises that npm will work with this version.\n" +
    'npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.\n' +
    'npm WARN npm You can find the latest version at https://nodejs.org/\n' +
    'npm ERR! cb.apply is not a function\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/mhdawson/.npm/_logs/2020-09-04T20_13_42_420Z-debug.log\n'
}
npm ERR! Test failed.  See above for more details.
```

**Comment by NickNaso** [comment]
CI:
CI:

| Version | Job | Status |
|---:|---|:---:|
| v15.x | ---| --- |
| v14.x | --- | --- |
| v12.x | ---| --- |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2741/ | ✓ |

**Comment by NickNaso** [comment]
CI:

| Version | Job | Status |
|---:|---|:---:|
| v15.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/  | ... |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2747/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2746/ | ✓ |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2745/ | ✓ |

**Comment by NickNaso** [comment]
CI:

| Version | Job | Status |
|---:|---|:---:|
| v15.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2755/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2756/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2757/ | ✓ |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2758/ | ✓ |

**Comment by mhdawson** [comment]
@NickNaso thanks, I assume this is now ready to land ?

**Comment by NickNaso** [comment]
@mhdawson Yes it's ready to be landed. Furthermore today I did another pass on the CI:

| Version | Job | Status |
|---:|---|:---:|
| v15.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2767/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2768/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2769/ | ✓ |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/2770/ | ✓ |

**Comment by mhdawson** [comment]
Landed as 6562e6b0ab604fd55b9c2d0cf954c9ce93e4bdee

**Pull request closed without merging**
