### PR TITLE
Make Buffer extend Uint8Array instead of directly extending Object

### PR DESCRIPTION
**Pull request by sampsongao**
For issue: https://github.com/nodejs/node-addon-api/issues/109

### CODE REVIEW

**Comment by mhdawson** [comment]
@sampsongao can you confirm that you don't think this change will require updates to any existing code using node-addon-api ?

**Comment by sampsongao** [comment]
No change on modules is needed.

**Comment by mhdawson** [comment]
@sampsongao thanks landing.

**Comment by mhdawson** [comment]
Landed as 74de0cb69f0af845195e242fe4dd5e4d12eb53c2

**Pull request closed without merging**
