### PR TITLE
test: fix asyncworker test so it runs on 6.x

### PR DESCRIPTION
**Pull request by mhdawson**
Fixes: https://github.com/nodejs/node-addon-api/issues/296

### CODE REVIEW

**Comment by mhdawson** [comment]
@gabrielschulhof can you please review/approve.

**Comment by gabrielschulhof** [comment]
Maybe we should refine this to perform the async work irrespective of whether hooks are available or not, but to not create, nor check the result of the promise if the hooks are unavailable.

**Comment by mhdawson** [comment]
@gabrielschulhof I think it now does what you suggested.  It checks which version its running on and runs different tests on 6.x.

**Comment by mhdawson** [comment]
Going to land this without waiting the usual 48 hours as it fixes a regression and we have 2 approvals.

**Comment by mhdawson** [comment]
Also as an FYI, figured out how to have a run of the tests nightly on all of the LTS versions. Job is here:  https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/

The way it reports failures is not great as it's not clear which version the failure was on, but at least its a start and the info is available if you look at the console output for the top level job.

**Comment by mhdawson** [comment]
Landed as dd1191e086fc4beb42de8d359ede9ad3e6776c56

**Pull request closed without merging**
