### PR TITLE
test: load testModules automatically

### PR DESCRIPTION
**Pull request by RaisinTen**

### CODE REVIEW

**Comment by RaisinTen** [comment]
@mhdawson I have added the multilevel traversal feature and the explicit `'.js'` extension check as discussed in the meeting. Also added a TODO comment so that the filtering in this function is updated when the test filenames are changed into `test_*.js`.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@RaisinTen thanks for the recent PRs.  I'll give the other team members a bit of time to review and try to land this late next week.

**Comment by mhdawson** [comment]
Landed as 1c040eeb631a97fb8a81b0833e8675ed9810f7d6

**Pull request closed without merging**
