### PR TITLE
Split the object test into smaller tests (get/set/delete/hasOwnProperty)

### PR DESCRIPTION
**Pull request by romandev**
This change breaks the object test into smaller tests for the following
reasons:
  - Smaller tests are better than very large one. (e.g. readability)
  - Before this patch, we have missed some test cases. For example,
    there are four overloading versions of the deleteProperty() method,
    but we haven't tested them all until now.

### CODE REVIEW

**Comment by romandev** [comment]
@mhdawson PTAL

**Comment by romandev** [comment]
@mhdawson Thank you for review and I'll request another reviewer. Have a good vacation :)

**Comment by romandev** [comment]
@addaleax Could you please review this patch if you have a minute?

**Comment by mhdawson** [comment]
Ran the tests locally on linux and I got this failure:

```
Starting test suite

Running test 'arraybuffer'
Running test 'asyncworker'
Running test 'buffer'
Running test 'error'
Running test 'external'
Running test 'function'
Running test 'name'
Running test 'object/delete_property'
Running test 'object/get_property'
Running test 'object/has_own_property'
Running test 'object/object'
Running test 'object/set_property'
Tests aborted with SIGSEGV
npm ERR! Test failed.  See above for more details.
```

With this PR backed out the tests ran ok.

@romandev can you take a look.  You can run the tests with npm-test

**Comment by romandev** [comment]
@mhdawson Done. I've just fixed the error. Thank you!

**Comment by mhdawson** [comment]
@romandev thanks, landed as e90a80bfb5d46f13b6bff6ac37f944d9f1724cfd

**Pull request closed without merging**
