### PR TITLE
docs: add napi-rs in more resource section

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Review by NickNaso — COMMENTED** [review]
Hi @Brooooooklyn,
what do you think to add a new section `Other bindings` something like this:
### **Other bindings**
- **[napi-rs](https://napi.rs)**  - (Rust)

**Comment by Brooooooklyn** [comment]
@NickNaso I've added **Other bindings** section

**Review by NickNaso — APPROVED** [review]
LGTM

**Review by legendecas — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
