### PR TITLE
Fix ObjectWrap destructor from env exit under node_g

### PR DESCRIPTION
**Pull request by davedoesdev**
Only fails under debug buildtype (node_g)

Update: Also fails using release 12.16.3

#722

### CODE REVIEW

**Comment by mhdawson** [comment]
@davedoesdev thanks for submitting a PR for this.

Does the stack trace suggest is occurring from a path triggered by the gc. I've not had time yet but wanted to think through if it was a concern or not if that was occurring (also away for next few days so will probably be mid next week before I find time).

**Comment by davedoesdev** [comment]
@mhdawson it looks like it's when the environment is closing due to the worker thread exiting.
The handles are being cleaned up at that point.

**Comment by davedoesdev** [comment]
@mhdawson the test also fails under Node 12.16.3 release build!

**Comment by mhdawson** [comment]
Spent some time looking at this see https://github.com/nodejs/node/pull/33508

**Comment by mhdawson** [comment]
@davedoesdev https://github.com/nodejs/node/pull/33508 just landed which should fix the reported problem (it will need to land in 14.x and 12.x as well).

I still think adding the test on the node-addon-api side makes sense in addition to the one in core.  Can you remove the non-test change and then we'll get it landed once the core backports are complete.

**Comment by davedoesdev** [comment]
@mhdawson done

**Comment by mhdawson** [comment]
@davedoesdev thanks, may be a while before we can land as we have to wait for Node.js backports but thanks for all of your working finding and helping to resolve. Much appreciated.

**Comment by davedoesdev** [comment]
@mhdawson no worries. Any rough ETA?

**Comment by mhdawson** [comment]
@davedoesdev sorry for the late update. Looks like its been backported as far back as 12.x.  I can't remember if we thought it would apply to 10.x but if you update the PR to just add the test we can run the CI and confirm one way or the other, and if not land it.

**Comment by davedoesdev** [comment]
@mhdawson PR should already have been updated to contain just the test

**Comment by mhdawson** [comment]
Added commit to only run on Node.js 12 and higher as it requires worker threads

**Comment by mhdawson** [comment]
Landed as: 518cfdcdc10301723b9d48848e8297f43dc54209

**Comment by mhdawson** [comment]
Thanks for all your work on this @davedoesdev

**Comment by davedoesdev** [comment]
@mhdawson thanks for merging

**Pull request closed without merging**
