### PR TITLE
[WIP] Add test coverage report with gcovr 

### PR DESCRIPTION
**Pull request by JckXia**

### CODE REVIEW

**Comment by KevinEady** [comment]
Looking at the results in the above report, I'm not sure how accurate it is...? For example, it is reporting that `ThreadSafeFunction::New(napi_env, const Function&, ResourceString, size_t, size_t)` is [not covered](https://app.codecov.io/github/KevinEady/node-addon-api/commit/a7fe535d9371c2e1cc752366fa86eca13aee063a/blob/napi-inl.h#L5741), but we have it in a test [here](https://github.com/nodejs/node-addon-api/blob/afa494ef7f95148a1388813d69628e6367d6f600/test/threadsafe_function/threadsafe_function_unref.cc#L37).

**Comment by KevinEady** [comment]
With optimizations off, [file explorer](https://app.codecov.io/github/KevinEady/node-addon-api/commit/86f03b832a04ffd16a5fbd3e5562e5f476d9fd33/tree)

**Comment by JckXia** [comment]
Hey @KevinEady! Thank you so much for taking a look into this. I ran this command:
 `gcovr --gcov-filter '.*\b(napi-inl.h)|(napi.h)\b' -r $(cd ../../ && pwd) --html --html-details -o ../../coverage/cxxcov_deets.html` from `test/build` and got a coverage score of 94.2% for `napi-inl.h`. Coverage data for `napi.h` seems to be missing, however.

On a side note, initially `ThreadSafeFunction::New(napi_env, const Function&, ResourceString, size_t, size_t)` was shown to be uncovered. However, it was shown as "covered" on a subsequent invocation of the command.

**Comment by KevinEady** [comment]
Hi @JckXia , Which compiler + version are you using?

**Comment by JckXia** [comment]
I am using g++ 11.3.0 on ubuntu
```
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by por1981** [comment]
> _ No description provided. _

https://github.com/nodejs/node-addon-api/pull/1318#issue-1706481942

**Pull request closed without merging**
