### PR TITLE
add doc auto deploy action

### LINKED ISSUE #674: Auto publishing doc using github actions.
With this we can simplify doc publish process.

Ref: https://github.com/JamesIves/github-pages-deploy-action.

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix #674

See: http://www.gengjiawen.com/node-addon-api/.

After merging this, I will do add to `README.md` and other doc fix.

### CODE REVIEW

**Comment by mhdawson** [comment]
Can you add a bit more details as to what this is doing?  At some point I think we were going to delete the generated doc, so not sure if this is related to that or not?

**Comment by gengjiawen** [comment]
> At some point I think we were going to delete the generated doc

Why ? It the doc outdated or something ?

**Comment by legendecas** [comment]
I believe the docs under `/doc` directory are recommended to use.

**Comment by gengjiawen** [comment]
> I believe the docs under `/doc` directory are recommended to use.

The generated doc is `yarn run doc` in package.json. So the generated doc is using source from `/doc` folder.

**Comment by legendecas** [comment]
IIUC, doxygen doesn't read these markdown files in `/doc`.

**Comment by gengjiawen** [comment]
I see, we are going to remove doxygen part in current doc system ?

**Comment by mhdawson** [comment]
@gengjiawen that was the plan, we have been remiss in not removing it.

**Pull request closed without merging**
